name: Linter

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16
          check-latest: true
      - run: npm install
      - run: npm run eslint
